### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by pmayer** [NatLibFi/Skosmos-client#2]
I'm interested to know if this project is still active, because nobody ever responded to my pull request. Otherwise I'm thinking about starting a fork for my needs.

**Comment by osma** [comment]
Hi @pmayer , sorry that you had to wait for a response to your PR. I will try to review it soon.

This project isn't dead, it's only [resting](http://montypython.50webs.com/scripts/Series_1/53.htm) :)
